### ISSUE TITLE
REGION PROJECT | CRMP

### ISSUE THREAD

**Issue by MisterJoule** [Tiaansu/samp-discord-rpc#3]
RE
![btDVdl2Xxlw](https://github.com/Tiaansu/samp-discord-rpc/assets/174159514/1581cd19-2e0a-44b6-bb28-eb8b8814c7d0)
GION PROJECT | CRMP - https://vk.com/region.crmp

**Comment by Tiaansu** [comment]
Hello! I think you forgot to read [this](https://github.com/Tiaansu/samp-discord-rpc?tab=readme-ov-file#note). I'm only accepting a single server right now.
